#
# Build usable documents
#

ASCIIDOCTOR = asciidoctor
ASCIIDOCTOR_PDF = $(ASCIIDOCTOR)-pdf
OPTIONS := --trace \
           -a toc \
           -a compress \
           -a mathematical-format=svg \
           -a pdf-fontsdir=docs-resources/fonts \
           -a pdf-theme=docs-resources/themes/riscv-pdf.yml \
           --failure-level=ERROR
REQUIRES := --require=asciidoctor-bibtex \
            --require=asciidoctor-diagram \
            --require=asciidoctor-mathematical
DITAA = ditaa
DEPS = src/contributors.adoc
DEPS += src/changelog.adoc
DEPS += src/intro.adoc
DEPS += src/terms.adoc
DEPS += src/binary-encoding.adoc
DEPS += src/ext-base.adoc
DEPS += src/ext-legacy.adoc
DEPS += src/ext-time.adoc
DEPS += src/ext-ipi.adoc
DEPS += src/ext-rfence.adoc
DEPS += src/ext-hsm.adoc
DEPS += src/ext-sys-reset.adoc
DEPS += src/ext-pmu.adoc
DEPS += src/ext-debug-console.adoc
DEPS += src/ext-sys-suspend.adoc
DEPS += src/ext-cppc.adoc
DEPS += src/ext-nested-acceleration.adoc
DEPS += src/ext-steal-time.adoc
DEPS += src/ext-sse.adoc
DEPS += src/ext-firmware-features.adoc
DEPS += src/ext-experimental.adoc
DEPS += src/ext-vendor.adoc
DEPS += src/ext-firmware.adoc
DEPS += src/references.adoc
DEPS += src/references.bib
IMAGES = images/riscv-sbi-intro1.png
IMAGES += images/riscv-sbi-intro2.png
IMAGES += images/riscv-sbi-hsm.png
IMAGES += images/riscv-sbi-sse-sm.png
REVSNIP = $(SPEC)/autogenerated/revision.adoc-snippet
TARGETS = riscv-sbi.pdf
TARGETS += riscv-sbi.html
TARGETS += $(REVSNIP)
COMMITDATE=$(shell git show -s --format=%ci | cut -d ' ' -f 1)
GITVERSION=$(shell git describe --tag)
SPEC=$(shell pwd)

.PHONY: all
all: $(IMAGES) $(TARGETS)

images/%.png: src/%.ditaa
	rm -f $@
	$(DITAA) $< $@

%.html: %.adoc $(IMAGES) $(REVSNIP) $(DEPS)
	$(ASCIIDOCTOR) -d book -b html $<

%.pdf: %.adoc $(IMAGES) docs-resources/themes/riscv-pdf.yml $(REVSNIP) $(DEPS)
	$(ASCIIDOCTOR_PDF) $(OPTIONS) $(REQUIRES) --out-file=$@ $<

$(SPEC)/autogenerated:
	-mkdir $@

$(SPEC)/autogenerated/revision.adoc-snippet: Makefile $(SPEC)/autogenerated
	echo ":revdate: ${COMMITDATE}" > $@-tmp
	echo ":revnumber: ${GITVERSION}" >> $@-tmp
	(test -f $@ && diff $@ $@-tmp) || mv $@-tmp $@

.PHONY: clean
clean:
	rm -f $(TARGETS)
	rm -rf $(SPEC)/autogenerated

.PHONY: install-debs
install-debs:
	sudo apt-get install pandoc asciidoctor ditaa ruby-asciidoctor-pdf

.PHONY: install-rpms
install-rpms:
	sudo dnf install ditaa pandoc rubygem-asciidoctor rubygem-asciidoctor-pdf
